### ISSUE TITLE
Improving the `plot` section

### ISSUE THREAD

**Issue by tapyu** [cetz-package/docs#2]
Hi, I really want to contribute the [`plot` section](https://cetz-package.github.io/docs/libraries/plot.html), but it seems really confusing how you want to organize the section. I want to add parameters such as `x-tick-step`, `x-ticks`, `x-min`, `y-min`, ... from the `plot.plot()` function, but I am not sure where it goes....

**Comment by fenjalien** [comment]
Hi! That part of the docs is intended to be more tutorial focused, a description of _how_ to use CeTZ. We're planning on adding an API/reference section that goes into the specifics of _what_ exists in CeTZ, it'll use the doc strings in the source code.

For the format of the section itself, we don't have any ideas so do what feels right! Once you make the pr we can suggest changes and give feedback :)
